# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Hung Q. Pham
title: Ph.D. candidate at the department of Chemistry, University of Minnesota
email: pqh3.14@gmail.com
# phone: Your phone number (optional)
# website: Your website (eg. https://google.com)(optional)

# Social links
# twitter_username: jekyllrb
github_username:  hungpham2017
# dribbble_username: jekyll
# facebook_username: 
linkedin_username: hung-pham-4b46598b

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Hung and I'm a Ph.D. candidate at the department of chemistry, University of Minnesota.

  #You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
  #  - Lists
  #  - Tables
  #  - Links
  #  - Images

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in quantum chemistry and software engineering some of my other interests and hobbies are:
   - EDM
   - Karate
   
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
