# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Hung Q. Pham
title: Research Scientist | Ph.D. in Quantum Chemistry
email: pqh3.14@gmail.com
# email_title: Email (Email title override)
phone: 612-231-6Nine8Nine
# phone_title: Phone (Phone title override)
website: hungqpham.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: hungpham314
github_username:  hungpham2017
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: thequguy
linkedin_username: hung-q-pham-4b46598b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: /0000-0003-3608-1298
googlescholar_username: MIe6vYUAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: fab fa-google-scholar
#   url: Link url (eg. https://google.com)

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/hp.jpeg
about_content: | # this will include new lines to allow paragraphs
  *Quantum chemistry isn’t just equations and code — it’s a gateway to revolutionize energy, pharmaceuticals, and materials. I’m passionate about closing the gap between academic research and real-world impact, crafting innovative tools and solutions that transform industries.*

  I am a research scientist at ByteDance Research, where I design cutting-edge quantum chemical algorithms grounded in electronic structure theory. My work delivers scalable, high-precision ab initio simulations on both classical high-performance systems and emerging quantum computers. With a knack for turning complex theory into practical software, I’ve optimized simulations—like scaling computations to over 20,000 orbitals and achieving 10–100x speed-ups—pushing the boundaries of efficiency and accuracy. My expertise spans computational chemistry and materials science, with applications in quantum technology, renewable energy, pharmaceuticals, and beyond, driving high-quality data for AI+Science and sparking transformative industrial innovations. During my Ph.D. at the University of Minnesota, Twin Cities, under Professor Laura Gagliardi, I pioneered quantum embedding techniques using density matrix and multiconfigurational methods for molecules and periodic solids. As a postdoctoral researcher at Columbia University with Professor David Reichman, I advanced auxiliary-field quantum Monte Carlo methods, expanding their reach with novel algorithmic breakthroughs.

  Years of tackling computational science have forged my diverse skill set in software development, mathematical modeling, convex optimization, and data analysis, sharpened on HPC and cloud platforms. I’ve built numerical models and simulations for quantum chemistry, wielding both deterministic and stochastic algorithms to span classical and quantum realms—a journey that’s honed my research prowess and given me a wide-angle view of complex systems. This versatile toolkit, rooted in rigorous problem-solving, seamlessly transfers to software engineering, data science, and quantitative research, where I’m poised to drive innovation and deliver results.

  <a href="https://hungqpham.com/assets/resume.pdf" target="_blank">View My Resume</a>

#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#    - Lists
# ges/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: Quantum AI: Science to Finance
        # link: https://github.com/hungpham2017/pDMET
        # link_text: Link Text
        additional_links:
        quote: >
        I’m boldly diving into AI/ML applications, leveraging techniques such as classical ML, deep learning, and large language models to revolutionize materials discovery through high-fidelity quantum chemical data, while also exploring their potential to address FinTech challenges in portfolio optimization, risk management, and financial modeling. Through independent side projects, I’m honing a dynamic skill set in computational science, numerical simulations, high-performance computing, and statistical algorithms. This expertise is primed for quantum technologies, data science, and AI-driven innovation across industries.
        description: | # this will include new lines to allow paragraphs
        I ha
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: Quantum Embedding
        # link: https://github.com/hungpham2017/pDMET
        # link_text: Link Text
        additional_links:
          - title:  pDMET
            icon: fab fa-github
            url: https://github.com/hungpham2017/pDMET
        quote: >
          Scalable Quantum Embedding and Quantum Algorithms for Material Simulation
        description: | # this will include new lines to allow paragraphs
        I have contributed to developing quantum embedding algorithms for efficient, 1 kcal/mol-accurate ab initio simulations of strongly correlated and metallic systems on classical and quantum platforms, advancing quantum chemistry applications in areas like catalysis, superconductors, and quantum computing. My work has honed a versatile skill set, including mathematical modeling (with expertise in linear algebra), scientific computing, and software engineering—spanning theory to production code in Python, C/C++, and legacy Fortran. These skills, bridging theoretical insights and practical implementation, are highly transferable to quantum technologies and data science, enabling impactful solutions across diverse challenges.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: Quantum Monte Carlo
        # link: https://github.com/hungpham2017/pDMET
        # link_text: Link Text
        additional_links:
          - title:  pDMET
            icon: fab fa-github
            url: https://github.com/hungpham2017/pDMET
        quote: >
          Large-scale Quantum Monte Carlo
        description: | # this will include new lines to allow paragraphs
        Leveraging locality and modern GPUs, I have contributed to developing advanced algorithms and applying AFQMC methods, enabling scalable, chemically accurate quantum chemistry simulations for large systems, including strongly correlated molecules and metallic surfaces. This work has expanded my expertise into stochastic methods, particularly Monte Carlo simulations, which are fundamentally distinct from deterministic quantum chemistry approaches.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: Computational Design of Novel Materials
        # link: https://github.com/hungpham2017/pDMET
        # link_text: Link Text
        additional_links:
          - title:  MCU
            icon: fab fa-github
            url: https://github.com/hungpham2017/mcu
          - title:  pWannier90
            icon: fab fa-github
            url: https://github.com/hungpham2017/pyWannier90
        quote: >
          Computational chemistry applied to Topological Insulator | Perovskites | MOFs | COFs
        description: | # this will include new lines to allow paragraphs
        I have applied advanced and cusotmzized computational techniques and analysis based on quantum chemistry, including periodic quantum chemistry vand DFT, Wannier-based tight-binding models, and Grand Canonical Monte Carlo simulations, to investigate materials such as reticular frameworks, topological systems, and photovoltaics, identifying novel materials with unique properties for industrial applications. This work has strengthened my versatile skill set in bring theories to actual problems where innovative solution is needed to solve these fundamental appklcaitions changles
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: GPU-Accelerated Quantum Chemistry
        # link: https://github.com/hungpham2017/pDMET
        # link_text: Link Text
        # additional_links:
        #   - title:  MCU
        #     icon: fab fa-github
        quote: >
          Fast Quantum Chemistry on GPU
        description: | # this will include new lines to allow paragraphs
        To elevate quantum chemistry as a vital industrial technology beyond standard DFT, computational speed is essential. I have contributed to accelerating quantum chemistry by leveraging GPUs, enhancing its practicality for real-world applications. My efforts focus on optimizing advanced methods, such as random phase approximation and quantum embedding, harnessing GPU power to drive industrial adoption.
  - title: Experience
    layout: list
    content:
      - layout: top-right
        title: ByteDance Research
        sub_title: Research Scientist
        # caption: March 2022 - Current
        link: March 2022 - Current
        # quote: >
        #    Short description of the company (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Scalable Quantum Chemical Solutions for Industry
      - layout: top-right
        title: Columbia University
        sub_title: Postdoctoral Research Scientist
        caption: "Advisor: David Reichman"
        link: June 2021 - March 2022
        # quote: >
        #    Short description of the company (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Quantum Monte Carlo for quantum chemistry
      - layout: top-right
        title: University of Minnesota, Twin Cities
        sub_title: Research Assistant
        caption: "Advisor: Laura Gagliardi"
        link: Jan 2017 - May 2021
        # quote: >
        #    Short description of the company (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Quantum embedding, Computational materials science, Photovoltaics
      - layout: top-right
        title: Center for Molecular and NanoArchitecture (MANAR)
        sub_title: Research Assistant
        # caption: Oct 2011 - Jul 2015
        link: Oct 2011 - Jul 2015
        # quote: >
        #    Short description of the company (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Periodic DFT, Grand canonical Monte Carlo, Reticular chemistry
      - layout: top-right
        title: Institute for Computational Science and Technology
        sub_title: Research Assistant
        caption: "Advisor: Nguyen-Nguyen Pham-Tran"
        link: Oct 2011 - Jul 2015
        # quote: >
        #    Short description of the company (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Periodic DFT, Grand canonical Monte Carlo, Reticular chemistry

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University of Minnesota, Twin Cities
        sub_title: Ph.D. in Chemistry
        link: Aug 2015 - May 2021
        # quote:Aug 2015 - May 2021
        #  Short institution or course description (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Description of qualification

      - layout: top-right
        title: VNUHCM - University of Science
        sub_title: B.S. in Chemistry
        link: Sep 2007 - Sep 2011
        # quote: >
        #  Short institution or course description (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Description of qualification

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I’m passionate about exploring science, especially when it comes to quantum topics and cool technology. I love discussing futuristic visions and staying on top of the latest innovations. On weekends, I recharge at EDM festivals, catching my favorite DJs. I balance being both an introvert and extrovert—focused and ambitious during the workweek, but always ready to relax with good music and great conversations. I’m also active on social media, where I enjoy sharing ideas about science and technology. Whether at a cocktail bar or a coffee shop, a cold brew always keeps me inspired.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
