# Site
repository: hungpham2017/mcu
# favicon: images/favicon.ico

# Personal info
name: Hung Q. Pham
title: Ph.D. candidate at Department of Chemistry, University of Minnesota
email: pqh3.14@gmail.com
#website: https://github.com/hungpham2017

# Social links
#twitter_username: facespics
github_username: hungpham2017
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: hung-pham-4b46598b
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Hung and I'm a Ph.D. candidate at the department of chemistry, University of Minnesota.

#  I am most skilled in: <mark>Python</mark> and <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in quantum chemistry and software engineering some of my other interests and hobbies are:
   - EDM
   - Karate

# Footer
footer_show_references: true

# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
